version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  build:
    macos:
      xcode: "15.2.0"
    steps:
      - checkout
      - run:
          name: Print Working Directory
          command: pwd
      - run:
          name: List Files in Current Directory
          command: ls -la
      - run:
          name: Install SwiftLint
          command: brew install swiftlint
      - run:
          name: Lint Swift Code
          command: swiftlint lint --reporter junit | tee lintResult.xml
      - store_artifacts:
          path: lintResult.xml

  ios-deploy:
    macos:
      xcode: "15.2.0"
      resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - macos/switch-ruby:
          version: "3.0"
      - run:
          name: Print Working Directory (before fastlane)
          command: pwd
      - run:
          name: List Files in Current Directory (before fastlane)
          command: ls -la
      - run:
          name: Install Bundler and Dependencies
          command: |
            gem install bundler  # Install bundler if not already installed
            bundle install  # Install required Ruby gems from the Gemfile
      - run:
          name: Run Fastlane Dev Lane
          command: bundle exec fastlane dev

workflows:
  build-and-deploy-wf:
    jobs:
      - build
      - ios-deploy:
          requires:
            - build